### ISSUE TITLE
Question: How does tmux-exec work if I'm already in a tmux session?

### ISSUE THREAD

**Issue by yamlCase** [predatorray/kubectl-tmux-exec#7]
I spend 100% of my time inside tmux sessions already.  How does tmux-exec handle that?  Does it nest ?  or does it detect it and just split panes in a windows?

**Comment by predatorray** [comment]
Actually, tmux-exec simply executes `tmux` commands even if you are in a session already. You may possibly run into problems like `sessions should be nested with care, unset $TMUX to force`.

Though unsetting the env var could be a workaround, it is, indeed, nice to just split panes in an existing session instead of nesting it. Will consider adding this feature in a future release.

**Comment by predatorray** [comment]
Hi, @yamlCase. I have just released [version 0.1.1](https://github.com/predatorray/kubectl-tmux-exec/releases/tag/v0.1.1). The plugin can now automatically reuse your existing tmux session. Hope it will help you.

**Comment by predatorray** [comment]
Please feel free to leave a comment here or open another issue if you have any other questions.
